# Generated by Django 5.0.9 on 2025-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('q1', models.TextField(blank=True)),
                ('q2', models.TextField(blank=True)),
                ('q3', models.TextField(blank=True)),
                ('q4', models.TextField(blank=True)),
                ('generated_script', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
