# Generated by Django 5.0.9 on 2025-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysession',
            name='user_script_modification',
            field=models.TextField(blank=True),
        ),
    ]
