# Generated by Django 5.0.9 on 2025-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_storysession_user_script_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysession',
            name='videogen_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
