# Generated by Django 5.0.9 on 2025-05-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_storysession_videogen_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('prompt_template', models.TextField(help_text='Use {{story}} as a placeholder for the user story.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
