# Generated by Django 5.0.9 on 2025-05-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_promptconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptconfig',
            name='use_as_default',
            field=models.BooleanField(default=False),
        ),
    ]
