# Generated by Django 4.2.21 on 2025-06-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_downloademail'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysession',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
    ]
