# Generated by Django 4.2.21 on 2025-06-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_storysession_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storysession',
            name='generated_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
