# Generated by Django 4.2.21 on 2025-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_storysession_generated_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storysession',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
