# Generated by Django 4.2.21 on 2025-06-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_storysession_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storysession',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
