# Generated by Django 4.2.21 on 2025-06-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_storysession_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysession',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
